"""Your message here

Revision ID: d19d9cdc5c71
Revises: 1f2fdc75e8c1
Create Date: 2025-05-25 09:13:18.144674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19d9cdc5c71'
down_revision = '1f2fdc75e8c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
